name: Run Hello World and LS

on:
  workflow_call:   # Solo workflow_call, sin workflow_dispatch

jobs:
  run-inline-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Ejecutar script
      - name: Exec HolaMundo y LS
        run: |
          echo "Hola Mundo"
          pwd
          ls -lah
          echo "Fin del Script"
          echo "ESTE ES UN PIPE DE TEST"